[tool.poetry]
name = "hello-world-django"
version = "0.1.0"
description = ""
authors = ["Bradley Marques <bradleyrcmarques@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.2"
Django = "^4.2.7"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
djlint = "^1.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
